In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/stockmarket-sentiment-dataset/stock_data.csv


In [2]:
data = pd.read_csv("/kaggle/input/stockmarket-sentiment-dataset/stock_data.csv")
data.head()

Text  Sentiment
0  Kickers on my watchlist XIDE TIT SOQ PNK CPW B...          1
1  user: AAP MOVIE. 55% return for the FEA/GEED i...          1
2  user I'd be afraid to short AMZN - they are lo...          1
3                                  MNTA Over 12.00            1
4                                   OI  Over 21.37            1

In [3]:
X = data.Text
y = data.Sentiment

In [4]:
X

0       Kickers on my watchlist XIDE TIT SOQ PNK CPW B...
1       user: AAP MOVIE. 55% return for the FEA/GEED i...
2       user I'd be afraid to short AMZN - they are lo...
3                                       MNTA Over 12.00  
4                                        OI  Over 21.37  
                              ...                        
5786    Industry body CII said #discoms are likely to ...
5787    #Gold prices slip below Rs 46,000 as #investor...
5788    Workers at Bajaj Auto have agreed to a 10% wag...
5789    #Sharemarket LIVE: Sensex off day’s high, up 6...
5790    #Sensex, #Nifty climb off day's highs, still u...
Name: Text, Length: 5791, dtype: object

In [5]:
y

0       1
1       1
2       1
3       1
4       1
       ..
5786   -1
5787   -1
5788    1
5789    1
5790    1
Name: Sentiment, Length: 5791, dtype: int64

In [6]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [7]:
ps = PorterStemmer()
lammat = WordNetLemmatizer()
corpus = []

In [8]:
for i in range(len(X)):
    review = re.sub('[^a-zA-Z]', " ", X[i])
    review = review.lower()
    review = review.split()
    ## review = [ps.stem(word)for word in review if not word in set(stopwords.words('english'))]
    review = [lammat.lemmatize(word)for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['kicker watchlist xide tit soq pnk cpw bpz aj trade method method see prev post',
 'user aap movie return fea geed indicator trade year awesome',
 'user afraid short amzn looking like near monopoly ebooks infrastructure service',
 'mnta',
 'oi',
 'pgnx',
 'aap user current downtrend break otherwise short term correction med term downtrend',
 'monday relative weakness nyx win tie tap ice int bmc aon c chk biib',
 'goog ower trend line channel test volume support',
 'aap watch tomorrow ong entry',
 'assuming fcx open tomorrow trigger buy still much like setup',
 'really worry everyone expects market rally usually exact opposite happens every time shall see soon bac spx jpm',
 'aap gamco arry haverty apple extremely cheap great video',
 'user maykiljil posted agree msft going higher possibly north',
 'momentum coming back etfc broke resistance solid volume friday ong set',
 'ha hitting mean resume targeting level',
 'user gameplan shot today liked trend break may c h break oc weekly tren

In [10]:
import numpy as np    
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_new = cv.fit_transform(corpus).toarray()
y_new = np.array(y)

In [11]:
X_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
y_new

array([1, 1, 1, ..., 1, 1, 1])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size=0.3)

In [14]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [15]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [16]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [17]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

          -1       0.63      0.65      0.64       612
           1       0.81      0.79      0.80      1126

    accuracy                           0.74      1738
   macro avg       0.72      0.72      0.72      1738
weighted avg       0.74      0.74      0.74      1738



In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[397, 215],
       [233, 893]])